pull_request_rules:
  - name: approved merges
    actions:
      merge:
        method: squash
        strict: true
        commit_message: title+body
      delete_head_branch: {}
      label:
        add: ["Status: Merged"]
        remove: ["Status: Revision Needed", "Status: Pending", "Status: Review Needed", "Status: Accepted", "Status: Blocked", "Status: In Progress", "Status: NotReproduced"]
    conditions:
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
  - name: buildbot auto merges
    actions:
      review:
        type: APPROVE
        message: "automatic approve because author=metworkbot"
    conditions:
      - -merged
      - -closed
      - author=metworkbot
  - name: master branch
    actions:
      comment:
        message: |
          Thank you for contributing to this project.

          But we don't accept pull requests on `master` branch as said in our
          contributing guide.

          => You have to change the base branch of your pull request to
          `integration` branch.

           It's very easy to do that by following this [github guide](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request).

           Many thanks!
      label:
        add: ["Status: Revision Needed"]
        remove: ["Status: Pending", "Status: Review Needed", "Status: Accepted", "Status: Blocked", "Status: Closed", "Status: In Progress", "Status: NotReproduced"]
    conditions:
      - base=master
      - -closed
